// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from 'prisma/config';
import { readFileSync } from 'fs';
import { resolve } from 'path';

function loadEnvDatabaseUrl(): string | undefined {
    if (process.env.DATABASE_URL) {
        return process.env.DATABASE_URL;
    }

    try {
        const envPath = resolve(process.cwd(), '.env');
        const raw = readFileSync(envPath, 'utf8');
        for (const line of raw.split(/\r?\n/)) {
            const trimmed = line.trim();
            if (!trimmed || trimmed.startsWith('#')) {
                continue;
            }

            const separatorIndex = trimmed.indexOf('=');
            if (separatorIndex === -1) {
                continue;
            }

            const key = trimmed.slice(0, separatorIndex).trim();
            const value = trimmed.slice(separatorIndex + 1).trim();
            if (key === 'DATABASE_URL' && value) {
                return value;
            }
        }
    } catch {
        // Fall through to the default fallback below.
    }

    return undefined;
}

export default defineConfig({
    schema: 'prisma/schema.prisma',
    migrations: {
        path: 'prisma/migrations'
    },
    datasource: {
        url: loadEnvDatabaseUrl() || 'postgresql://user:password@localhost:5432/db'
    }
});
